#Numpy
NumPy (Numerical Python) is an open source Python library which supports Mulidimensional array and matrix datastructure.

In [72]:
import numpy as np
#importing numpy 

##Creating One Dimensional array

In [73]:
n1 = np.array([1,2,5,4]) # Creating an array
print("Given Array is {}".format(n1))
print("Order of the matrix is {}".format(n1.shape)) # returns order of the matrix


Given Array is [1 2 5 4]
Order of the matrix is (4,)


##Creating Two Dimensional Array 

In [74]:
n2 = np.array([[1,6],[8,4]]) # Creating an array
print("Given Array is {}".format(n2))
print("Order of the matrix is {}".format(n2.shape)) # returns order of the matrix

Given Array is [[1 6]
 [8 4]]
Order of the matrix is (2, 2)


##Inspecting an Array

In [75]:
print(n1.shape) #Array dimension
print(len(n2)) #Length of array
print(n1.size) #Number of Array elements
print(n1.ndim) #Number of Array dimensions
print(n1.dtype) #Datatype of Array
print(n1.dtype.name)#Name of datatype
print(n1.astype(int)) #Convert an array to a different type

(4,)
2
4
1
int32
int32
[1 2 5 4]


##Arithmetic Operations

In [92]:
n4 = np.array([5,6,7,8])

print("Sum : {}".format(np.add(n4,n1))) #Addition
print("Sub : {}".format(np.subtract(n4,n1))) #Subtreaction
print("Division : {}".format(np.divide(n4,n1))) #Division
print("Multiply : {}".format(np.multiply(n4,n1))) #Multiplication
print("Exponential : {}".format(np.exp(n4))) #Exponential
print("Squareroot : {}".format(np.sqrt(n4))) #Squareroot
print("Sin : {}".format(np.sin(n4))) #Sin Function
print("Cos : {}".format(np.cos(n4))) #Cos Function
print("Log : {}".format(np.log(n4))) # Log Function

Sum : [ 6  8 12 12]
Sub : [4 4 2 4]
Division : [5.  3.  1.4 2. ]
Multiply : [ 5 12 35 32]
Exponential : [ 148.4131591   403.42879349 1096.63315843 2980.95798704]
Squareroot : [2.23606798 2.44948974 2.64575131 2.82842712]
Sin : [-0.95892427 -0.2794155   0.6569866   0.98935825]
Cos : [ 0.28366219  0.96017029  0.75390225 -0.14550003]
Log : [1.60943791 1.79175947 1.94591015 2.07944154]


##NUMPY EXERCISES

##1.Program to know numpy version and configuration

In [76]:
print(np.__version__) #To know version
print(np.show_config()) #To know Configuration


1.23.3
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

##2.Program to test whether none of the elements of a given array is zero.

In [77]:
print("Original array : {}".format(n1))
print("To test Whether 0 is present or not")
print(np.all(n1)) # test an array elements evaluate to false.
if(np.all(n1)==True):
    print("No..0 is not present in the array")
else:
    print("Yes..0 is present in the array")

Original array : [1 2 5 4]
To test Whether 0 is present or not
True
No..0 is not present in the array


##3.Program to test whether any of the elements of a given array is non-zero.

In [78]:
print("Original array : {}".format(n2))
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(n2)) # test an array elements evaluate to True.
if(np.all(n2)==True):
    print("Yes..Non-zero element is present")
else:
    print("No..Non-zero element is not present")

Original array : [[1 6]
 [8 4]]
Test whether any of the elements of a given array is non-zero:
True
Yes..Non-zero element is present


##4.Program to test a given array element-wise for finiteness (not infinity or not a Number).

In [79]:
print("Original array : {}".format(n2))
print("Test a given array element-wise for finiteness:")
print(np.isfinite(n2)) 

Original array : [[1 6]
 [8 4]]
Test a given array element-wise for finiteness:
[[ True  True]
 [ True  True]]


##5.Aggregate Functions

In [80]:
print("Sum : {}".format(np.sum(n1))) #Sum
print("Min : {}".format(np.min(n1))) #Minimum
print("Max : {}".format(np.max(n1))) #Maximum
print("Mean : {}".format(np.mean(n1))) #Mean
print("Median : {}".format(np.median(n1))) #Median
print("Correlation Coefficient : {}".format(np.corrcoef(n1))) #Correletion Coefficient
print("Standard Deviation : {}".format(np.std(n1))) #Standard Deviation


Sum : 12
Min : 1
Max : 5
Mean : 3.0
Median : 3.0
Correlation Coefficient : 1.0
Standard Deviation : 1.5811388300841898


##6.Copying an Arrays

In [81]:
n3 = n1.view() #Viewing an Array
np.copy(n1) #Copying a Array
n3 = n1.copy() #Assigning a variable
print("Copied to n3 = {}".format(n3)) #print

Copied to n3 = [1 2 5 4]


##7.Sorting Arrays

In [82]:
print(np.sort(n1)) #Sorting
print(np.sort(n2))

[1 2 4 5]
[[1 6]
 [4 8]]
